name: pr3
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - lib/components/product.json
    - lib/components/images/kish.jpg
    - lib/components/images/know_name.jpg
    - lib/components/images/maximum_the_hormone.jpg
    - lib/components/images/radiohead.jpg
    - lib/components/images/supergrass.png
    - lib/components/images/wolfmother.jpg
    - lib/components/images/placeholder.png
  uses-material-design: true
